### ISSUE TITLE
color about log4js

### ISSUE THREAD

**Issue by wanzhou** [nomiddlename/log4js-node#304]
I start nodejs server by `nohup node server.js >logs/log.log 2>&1 &`, but the log file have some charactor make me doubtful ( `^[[32m, ^[[0m, ^[[39m`....... ).
Someone tell me it's a color control code, how can I remove it. 
pls help me,thanks.

**Comment by nomiddlename** [comment]
Those are the coloured output control codes, yes. Log4js by default will use the console appender, which is set up to use the colour codes for nice output. When that gets redirected to a file, the colour codes don't always work. Instead, if you configure log4js to use the file appender to write your logs to `logs/log.log` instead of redirecting the output, then it will by default use the basic layout which does not have any colour codes. Alternatively, you can configure the console appender to use the basic layout.

Check the examples for how to configure a file appender.

**Comment by wanzhou** [comment]
Ok, I know that, thanks for much
