### ISSUE TITLE
Metadata in logging event

### ISSUE THREAD

**Issue by lambrojos** [nomiddlename/log4js-node#341]
Hello, I would like to now if it is possible to add some custom metadata to the logging event which gets passed to the layout token functions.

To be more specific, my case is that I would like to create a token representing an hapi request id, and a token representing the currently logged in user id

Is that possible?

**Comment by nomiddlename** [comment]
It's not possible to add temporary metadata (like request-specific data) at the moment. You'd have to write something like the connect-logger which wraps a log4js logger and adds request-specific info. Alternatively, if your hapi request id or logged in user id can be exposed via a global service api that could work - if you write your custom token like this (example off the top of my head, may not actually work):
```
var requestData = require('some-external-module');
function token(loggingEvent) {
  return requestData.hapi();
}
```
You'd then have to configure log4js programmatically (call `log4js.configure` yourself) rather than via the log4js.json auto-loading.

**Comment by nomiddlename** [comment]
I'm happy to accept pull requests that implement [diagnostic contexts](https://wiki.apache.org/logging-log4j/NDCvsMDC), btw :)

**Comment by lambrojos** [comment]
Oh, interesting! I will try to make this part of my current project.

**Comment by ZzZombo** [comment]
I needed something like this, and ended up adding a custom token. Within the token you can set the event properties, and the token may return an empty string to leave no visible output.
