### ISSUE TITLE
Nothing logged after set 'category' on 'console' appender via log4js.configure(...)

### ISSUE THREAD

**Issue by micooz** [nomiddlename/log4js-node#430]
### environment

log4js version: v1.1.0
os: macOS Sierra 10.12.2
node version: v7.3.0

### reproduce

```
const log4js = require('log4js');

log4js.configure({
  appenders: [
    {
      'type': 'console',
      'category': 'console' // here I set category
    }
  ],
  replaceConsole: true
});

const logger = log4js.getLogger();

logger.info('some information'); // nothing out
```

I also notice that given an empty object to `log4js.configure({})` will break the output as well. Is that a expected behavior?

**Comment by nomiddlename** [comment]
The problem here is that you have configured the console appender to only be used with loggers in the `console` category, so you won't see any output unless you use `log4js.getLogger('console')`. If you don't supply a category for the appender, it will apply to all categories. Just remove the `category` line in your config to see all the output.

There's a separate issue about making validation of the configuration better  - #426, which should fix the problem you've found with `{}`

**Comment by micooz** [comment]
Got it, thx!
