### ISSUE TITLE
Writing to user home directory ~/

### ISSUE THREAD

**Issue by vjacek** [nomiddlename/log4js-node#478]
Writing to the user's home directory with the standard shortcut ( ~/ ) does not appear to be supported.  This would make development much easier when using multiple machines or environments.

My log4js-config.json file:
```
{
    "appenders": [
        {
            "type": "file",
            "filename": "~/logs/myLog.log",
            "category": "myLog"
        }, ...
}
```

This results in the creation of a new directory `~` *within* the directory where the logging application is running.

**Comment by nomiddlename** [comment]
`~` as a placeholder for the user's home directory is only standard in bash shells, and you're right there is no support for any kind of filename expansion or manipulation in log4js. It will use whatever you put in the field. You could work around this by calling `log4js.configure` in your code with an object instead of a file, and replacing the filename with `process.env.HOME + '/logs/myLog.log'`.

**Comment by vjacek** [comment]
> ~ as a placeholder for the user's home directory is only standard in bash shells

Makes sense.  Happy to close the issue now.

Thanks as well for the workaround!
