### ISSUE TITLE
question: Breaking the facade with v2

### ISSUE THREAD

**Issue by js-n** [nomiddlename/log4js-node#493]
Will v2 break libraries that depend on v1's interface? by libraries, I mean packages which only call `getLogger()` and then use the logging api (`logger.info()`, etc.)

From the v2-changes document, I see there are things which mostly benefit the application layer, and some changes to the appender api. However, I'd encourage you to think through how this can be done in a way that will not cause version range conflicts. A large part of the value of things like [SLF4J](https://www.slf4j.org/manual.html) is that its API hasn't changed in a very long time, and is unlikely to ever change in the future. This lets library developers depend on the api with confidence, knowing that application developers and ops people can make application logging decisions independently from the log data made available from the library.

**Comment by nomiddlename** [comment]
Totally appreciate the value of not breaking things where possible, and apart from the configuration and appender changes, I've tried to keep things the same. The breaking changes are the reason for the version number bump from 1.x to 2.

I don't think there are any changes that would affect libraries. `getLogger` will work the same (better even, since it will no longer leak references), and the logger instance functions (`logger.info`, etc) haven't changed. `logger.setLevel()` as a function has been replaced by `logger.level` as a property, but I wouldn't have thought a library would set that. 

One thing that would affect libraries is the change to the default configuration that sets the log level to 'OFF'. This means that users of a library would have to enable logging to see the messages now, where previously they would be logged to stdout and the user would not know how to get rid of them or where they came from.

There are definitely breaking changes for appenders. I've thought about providing a wrapper for v1 appenders so that they can be used with the v2 API, but haven't had much time to implement.

**Comment by js-n** [comment]
The problem with incrementing the major version is that it breaks a version range like "^1.0.0". That means if I have:
- AppA
  - log4js@^2.0.0
  - LibB
    - log4js@^1.0.0

they will each get their own instance of log4js, even after `npm dedupe`, because the version ranges are not compatible. So when LibB calls `getLogger()`, it will get different appenders than when AppB calls `getLogger()`

**Comment by nomiddlename** [comment]
Yep, understand the problem now, thanks. Any suggestions on how to deal with it? Are you familiar with any other npm libraries that have solved this problem? I'm totally open to suggestions to fix this, and I'd rather use a "standard" approach if possible.

I could provide a thin `log4js-api` lib that third-party libs could use instead of `log4js`, that just delegates to whatever log4js version is installed without including it in the dependencies. If log4js is not present, then it just quietly ignores logging statements. Would that work?

**Comment by js-n** [comment]
yes, I think that would work- that's the approach that SLF4J takes on the java side. On npm, the closest to that approach I found is a new project with few dependencies called [get-logger](https://www.npmjs.com/package/get-logger).

**Comment by nomiddlename** [comment]
Released in version 2.0.0
