### ISSUE TITLE
How to support both log4js 1.1.1 and 2.2.0 by 3rd party appenders?

### ISSUE THREAD

**Issue by okkez** [nomiddlename/log4js-node#507]
Hi, I'm https://github.com/fluent/fluent-logger-node maintainer.

I want to support new version of log4js 2.2.0 in fluent-logger-node (log4js appender for this module).
Also I want to support both log4js 1.x and 2.x in same module. How to do such a thing?

Could you help me?

**Comment by nomiddlename** [comment]
Your appender can tell the difference when it's being called by log4js 1.x instead of log4js 2.x - the exported `configure` function will be called with 4 arguments in 2.x, but only 2 (or 1) arguments in 1.x - does that help? The documentation includes a section on [writing your own appender for 2.x](https://nomiddlename.github.io/log4js-node/writing-appenders.html). Let me know if you need more information.

**Comment by okkez** [comment]
Thanks! I will support log4js 2.2.x as soon as possible.

**Comment by nomiddlename** [comment]
Closing this issue - nothing to do.
