### ISSUE TITLE
How to set the log cache ?

### ISSUE THREAD

**Issue by deepred5** [nomiddlename/log4js-node#516]
I want the log content reaches 8K then save them, how to set the log cache?

**Comment by nomiddlename** [comment]
You want the log messages kept in memory until they reach a size of 8Kb, and then want them written to a file? Log4js does not do that, sorry - mainly because it isn't safe (if your application crashes then you'll lose that 8Kb of logs). Perhaps if you explained why you want to do this, I might be able to help.

**Comment by nomiddlename** [comment]
Closing this one for now. If you want to provide more information, then please re-open.
