### ISSUE TITLE
Last patch release is breaking API

### ISSUE THREAD

**Issue by akermabon** [nomiddlename/log4js-node#567]
Last release is breaking the API as the configuration for appenders has changed.
With NPM version ^2.3.3 is used to declare my appenders as following:

```
appenders: [
    {
        type: 'dateFile',
        filename: '/var/log/store-catalog/store-catalog.log',
        pattern: '-yyyy-MM-dd',
        alwaysIncludePattern: false
    }
]
```

It is now broken in version 2.3.4 as appenders requires an object...

**Comment by nomiddlename** [comment]
The API changed a while ago, with the first 2.x release (hence the bump in major version number). What changed in 2.3.5 was the addition of a typescript definition. So if you've been using any 2.x release with the configuration above you should have got an error. You must have also upgraded your log4js dependency from 1.x (or 0.x) recently. Anyway, you'll need to change your config to get it to work with 2.x - take a look at this [guide](https://nomiddlename.github.io/log4js-node/migration-guide.html).

**Comment by akermabon** [comment]
> So if you've been using any 2.x release with the configuration above you should have got an error. 

This is not true. As I said in my post, I was using 2.3.3 for a long time with "appenders" option passed as an array and it was working fine.

I think the version bump should have been 3.x because it's breaking the api from 2.3.3 to 2.3.4

**Comment by nomiddlename** [comment]
Hi, the [first issue](https://github.com/nomiddlename/log4js-node/issues/500) raised that was caused by the configuration change ("appenders must be an object") was on July 12, not long after 2.0 was released. 
 
Here are all the [changes between v2.3.3 and v2.3.4](https://github.com/nomiddlename/log4js-node/compare/v2.3.3...v2.3.4). This was mainly to add a flag to turn off clustering support. There is nothing in there that would cause your issue. Is it possible you bumped the version of log4js to 2.3.3 in your package.json but did not run `npm install`?

**Comment by akermabon** [comment]
My bad, I just realized somebody updated the package.json so when I though we were using 2.3.x we were actually using 1.x, sorry for the false accusation :(
